return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    indent = { enable = false }, -- WARN: treesitter indent was buggy with html
    ensure_installed = {
      "lua",
      "c",
      "vim",
      "vimdoc",
      "query",
      -- lua, c, vim, vimdoc, and query should always be included
      "comment",
      "c_sharp",
      "css",
      "diff",
      "devicetree",
      "dockerfile",
      "git_rebase",
      "git_config",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "http",
      "javascript",
      "typescript",
      "json",
      "python",
      "regex",
      "rust",
      "sql",
      "scss",
      "yaml",
    },
  },
}
